### ISSUE TITLE
Minted tokens don't reflect "Explicit" flag

### ISSUE THREAD

**Issue by esot321c** [ergopad/pratir-backend#11]
From [EIP 0024](https://github.com/ergoplatform/eips/blob/master/eip-0024.md) in R8: 

> Whether the artwork is explicit content or not. The key is "explicit" and the value is 0x00 if it is not explicit and 0x01 if it is. If this key is not present the artwork is assumed to not be explicit content.

**Comment by esot321c** [comment]
This may just be that the /asset/info endpoint on Ergopad API doesn't show it.

**Comment by Luivatra** [comment]
R8 added in ergopad api, your guess was correct :)
