### ISSUE TITLE
Remover MinterAddress from Ergopad asset/info API

### ISSUE THREAD

**Issue by esot321c** [ergopad/pratir-backend#12]
Minter address fetch seems to be slowing these API calls down significantly. I have a quick way to do it in the frontend that uses ergo explorer, and it allows me to separate it out from displaying the cards. Can we have an option on the asset fetch to completely eliminate the minterAddress retrieval logic to speed up the API calls? I'm getting 12 second page loads with that in place.

**Comment by Luivatra** [comment]
minterAddress can now be fetched from /info/{tokenId}/minter and is removed from the main endpoint. also turned on caching
