### ISSUE TITLE
Need a way to know if packs are sold out

### ISSUE THREAD

**Issue by esot321c** [ergopad/pratir-backend#23]
We can check if a sale is sold out when `tokensTotal === 0`, however, this won't happen if all packs are sold, because the NFTs are still in the sale. 

This is needed to prevent people from trying to buy packs when there are none left, since they can still send their money and the smart contract will still build the tx for them without any error. 

This goes hand in hand with keeping a sale open for pack opening even if the sale itself has closed.

**Comment by esot321c** [comment]
I'm seeing one sale says SOLD_OUT as the status. The only problem is, that didn't happen until the sale wallet was drained, IE all packs were opened and all NFTs were distributed from that.

**Comment by Luivatra** [comment]
yeah so a sold out status per pack is needed
